# @package model
_target_: model.architecture.quasimetric_embeddings.QuasimetricEmbeddings
lightning_module: path  # Options: "rnn" or "path"
input_size: 1
latent_size: 64
action_input_size: 4
action_latent_size: 16
hidden_size: 64
vocab_size: null  # Will be computed automatically
dataset_type: "quasimetric_embeddings"  # Options: "path" (PathDataset with collate_fn) or "spread" (SpreadPathDataset without collate_fn) or "quasimetric_embeddings" (QuasimetricEmbeddingsDataset without collate_fn)

# Configurable metrics
enabled_metrics: []


enabled_gen_metrics: []
